package com.jackzilla.feednom.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jackzilla.feednom.entities.RssFeed;
import com.jackzilla.feednom.entities.RssFeedItem;

import com.jackzilla.feednom.entities.RssFeedDao;
import com.jackzilla.feednom.entities.RssFeedItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rssFeedDaoConfig;
    private final DaoConfig rssFeedItemDaoConfig;

    private final RssFeedDao rssFeedDao;
    private final RssFeedItemDao rssFeedItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rssFeedDaoConfig = daoConfigMap.get(RssFeedDao.class).clone();
        rssFeedDaoConfig.initIdentityScope(type);

        rssFeedItemDaoConfig = daoConfigMap.get(RssFeedItemDao.class).clone();
        rssFeedItemDaoConfig.initIdentityScope(type);

        rssFeedDao = new RssFeedDao(rssFeedDaoConfig, this);
        rssFeedItemDao = new RssFeedItemDao(rssFeedItemDaoConfig, this);

        registerDao(RssFeed.class, rssFeedDao);
        registerDao(RssFeedItem.class, rssFeedItemDao);
    }
    
    public void clear() {
        rssFeedDaoConfig.getIdentityScope().clear();
        rssFeedItemDaoConfig.getIdentityScope().clear();
    }

    public RssFeedDao getRssFeedDao() {
        return rssFeedDao;
    }

    public RssFeedItemDao getRssFeedItemDao() {
        return rssFeedItemDao;
    }

}
